spring.application.name=aerolinea-app
server.port=8085

# Para todo el proyecto (Cuidado: genera mucho ruido)
logging.level.root=DEBUG

# Solo para tu código (Recomendado)
logging.level.com.tu.paquete=DEBUG

# Para ver las consultas SQL de Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ---------------------------------------------------------------
# CONFIGURACIÓN DE LA BASE DE DATOS H2 EN MEMORIA
# URL de conexión con parámetro DB_CLOSE_DELAY=-1 para evitar
# pérdida de datos al cerrar conexiones temporales
# ---------------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:aerodb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ---------------------------------------------------------------
# CONFIGURACIÓN DE JPA/HIBERNATE
# Estrategia update: crea/actualiza automáticamente las tablas
# ---------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------------
# CONSOLA WEB H2
# Accesible en http://localhost:8080/h2-console
# ---------------------------------------------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm
